- hosts: "kubernetes"
  become: yes
  serial: 1
  tasks:
    - name: Mark node {{ ansible_hostname }} as unschedulable.
      shell: kubectl cordon {{ ansible_hostname }}
    - name: Drain node {{ ansible_hostname }}, even if there are pods not managed by a ReplicationController, Job, or DaemonSet on it.
      shell: kubectl drain --ignore-daemonsets --delete-emptydir-data {{ ansible_hostname }}
    - name: Reboot kubernetes one at a time
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
    - name: Mark node {{ ansible_hostname }} as schedulable.
      shell: kubectl uncordon {{ ansible_hostname }}
